### ISSUE TITLE
missing tests

### ISSUE THREAD

**Issue by sensorario** [senso-api/senso-api#2]

**Comment by AlessandroMinoccheri** [comment]
#7

**Comment by AlessandroMinoccheri** [comment]
Resolved with pull request [#7](https://github.com/senso-api/senso-api/pull/7)

**Comment by sensorario** [comment]
Hai mai usato i messaggi di commit per chiudere le pull request? Se il messaggio e' "[close #123] - bla bla bla", automaticamente viene chiusa la issue non appena mergi. https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by AlessandroMinoccheri** [comment]
No! Ma proverò :) grazie
